### ISSUE TITLE
Road map of the project

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/fmriprep-denoise-benchmark#1]
Had a short chat with @ltetrel and we have come up with an easier way to set up this project.

The aim of this project is to systematically quantify the impact of confound variables generated by fMRIPrep and create an workflow that can be excecute on different versions of fMRIPrep. This can be broken down into two parts: 

1. the analysis and report generation suite
2. the workflow combining the data aspect and output with tool such as datalad

Personally I am more confident with the first part and less so with working with datalad. Also the development of this analysis and report suite can be independent from running on real dataset. Hence one of the pargmatic way to start this project is, perhaps:

- start a separate repo to work on the analysis, as an installable command line tool, with a normal git workflow
- in the main project repository, work on the work flow aspect and add the analysis tool either as a sub-module or dependency.

**Comment by ltetrel** [comment]
And when you will finish that part, we will sync together on how to adapt https://github.com/SIMEXP/fmriprep-reproducibility so it suits your needs.

**Comment by htwangtw** [comment]
Short term aims:
 - [ ] Refactor and add test to the metric generation and improved speed (#12, #7 )
 - [ ] Curate atlas (#2, #19)

**Comment by htwangtw** [comment]
let's move on to the next stage!
