### ISSUE TITLE
QC-FC analysis is slow

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/fmriprep-denoise-benchmark#12]
https://github.com/SIMEXP/fmriprep-denoise-benchmark/blob/010a88ceaeb965ad5af98bd62c2e4c2fc0727d14/code/metrics/quality_control_connectivity.py#L21

Might need to check the implementation.

**Comment by ltetrel** [comment]
Could not find ds000288 on openneuro, but depending on the dataset, age and sex effect could be negligible?
This would drastically reduce the computation time (no more matrix inversion).

Also I know sometimes scipy can decrease performance, so it could be worthwhile checking with a manual implementation instead (thinking of [stats.pearsonr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html) here, you don't need the hypothesis testing for example, just go with the raw mat formula) ?

**Comment by htwangtw** [comment]
Oops should be ds000228

We do need the p-value. And the effect of age is relevant enough from my initial check

**Comment by htwangtw** [comment]
I decided to crunch this metric on the cluster....
