### ISSUE TITLE
Subject with no usable volumes after scrubbing

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/fmriprep-denoise-benchmark#3]
In Ciric 2017 there's no clear description on data quality control.
A possible scenario is high motion subject with no usable volume.
We might want to have a rough QC to exclude the subjects with too little usable volume?

**Comment by htwangtw** [comment]
Currently I am using a really liberal threshold (0.5 mm) for scrubbing. 0.2 mm with leave me with 20 subjects in ds000228.

**Comment by htwangtw** [comment]
Idea: It might worth to drop subjects that loses more than 20% of the volumes at 0.5 mm threshold for the all the strategies to ensure the basic data quality?

**Comment by pbellec** [comment]
Makes sense to me, yes.

Pierre

**Comment by htwangtw** [comment]
Metric generated....

**Comment by htwangtw** [comment]
oh this is done long ago
