### ISSUE TITLE
Automatic book built

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/fmriprep-denoise-benchmark#31]
1. Identify minimal dependency for building the book and add installation options accordingly.

```
jupyter-book
matplotlib
numpy
templateflow
seaborn
scipy
```

2. How to templateflow in the CI
3. Put the data at some place downloadable

**Comment by htwangtw** [comment]
This is crucial for submitting to neurolibre

**Comment by pbellec** [comment]
note that for neurolibre, data needs to be downloadable, and describes through a  `data_requirements.json` file which will be triggered by the `repo2data` tool. 

Building the book does not go through CI, but rather through a binder hub instance hosted by neurolibre. It is possible to test this type of build here: https://roboneuro.herokuapp.com/

Docs for neurolibre subimission is here: 
https://docs.neurolibre.org/en/latest/SUBMISSION_STRUCTURE.html
https://docs.neurolibre.org/en/latest/PREPARE.html

**Comment by htwangtw** [comment]
Did a inital pass and can build everything locally 
Remaining issues:
- Neurolibre / repo2docker doesn't like submodules, need to remove
- For the customised atlases, upload to zenodo or include in repo

**Comment by htwangtw** [comment]
Actually let's open a new issue
