### ISSUE TITLE
Use pyBIDS to index fmriprep output

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/fmriprep-denoise-benchmark#7]
Currently I have a lazy function to grab fmriprep data.
It would be the best to replace it with pybids so the pipeline can be reproduced on any fmriprep output.

**Comment by ltetrel** [comment]
For some examples check that: https://github.com/ccna-biomarkers/ccna_qc/blob/314f73b03904d377df984678dc9586f4e9ee6606/src/features/build_features.py#L167-L179

But keep in mind that pybids caching takes a while... But should be ok for the size of your dataset.
